### PR TITLE
Upgrade to Laravel framework 8 and Laravel Passport 10

### PR DESCRIPTION
**Pull request by cpxPratik**
Followed https://github.com/laravel/passport/blob/10.x/UPGRADE.md#upgrading-to-100-from-9x

### CODE REVIEW

**Comment by uddhab** [comment]
@cpxPratik you really want to merge this to master? what will happen to existing apps which uses this?

**Comment by cpxPratik** [comment]
@uddhab, Yes, it should be merged to master after it is tested. It will be tagged as major release so existing apps will not be updated inadvertently.

**Comment by uddhab** [comment]
@cpxPratik don't we need versioned branch too? how would we update previous major version if master is updated to latest one. What does other open source projects do for versioning and development?

**Comment by cpxPratik** [comment]
@uddhab Before merging this PR, we need to create `0.5.x` branch from current master for maintaining 0.5 release. I see Laravel doing it this way.

**Comment by uddhab** [comment]
@cpxPratik ok great. let me know when this is not draft. "Assignees" can be author meaning you. And the 'reviewers' is where you can put my name.

**Review by uddhab — APPROVED** [review]

**Pull request merged**
